import { IZone } from "@/types/zone";
import { IIncident } from "@/types/incident";
import { IAlert } from "@/types/alert";
import { IRoad } from "@/types/road";
import { ISensorData } from "@/models/SensorData";

export const initialZones: IZone[] = [
  // 3 CRITICAL ZONES
  {
    name: "Sohra (Cherrapunji)",
    district: "East Khasi Hills",
    state: "Meghalaya",
    latitude: 25.27,
    longitude: 91.73,
    rainfall: 210,
    soilMoisture: 91,
    slope: 43,
    historicalEvents: 8,
    historicalRisk: 90,
    riskScore: 94,
    riskLevel: "CRITICAL",
    recommendedAction: "Immediate field inspection and preparation of evacuation routes.",
  },
  {
    name: "Mangan Valley",
    district: "North Sikkim",
    state: "Sikkim",
    latitude: 27.51,
    longitude: 88.53,
    rainfall: 195,
    soilMoisture: 88,
    slope: 47,
    historicalEvents: 9,
    historicalRisk: 92,
    riskScore: 91,
    recommendedAction: "Evacuate high-slope settlements; establish emergency relief camps.",
    riskLevel: "CRITICAL",
  },
  {
    name: "Dima Hasao (Haflong)",
    district: "Dima Hasao",
    state: "Assam",
    latitude: 25.17,
    longitude: 93.02,
    rainfall: 185,
    soilMoisture: 87,
    slope: 40,
    historicalEvents: 7,
    historicalRisk: 86,
    riskScore: 89,
    recommendedAction: "Suspend rail and highway transit; deploy disaster response taskforce.",
    riskLevel: "CRITICAL",
  },

  // 12 HIGH RISK ZONES
  {
    name: "Shillong Hills",
    district: "East Khasi Hills",
    state: "Meghalaya",
    latitude: 25.57,
    longitude: 91.89,
    rainfall: 155,
    soilMoisture: 76,
    slope: 35,
    historicalEvents: 5,
    historicalRisk: 65,
    riskScore: 68,
    riskLevel: "HIGH",
    recommendedAction: "Inspect stormwater drainage outlets and stabilize vulnerable road embankments.",
  },
  {
    name: "Mawsynram Slopes",
    district: "East Khasi Hills",
    state: "Meghalaya",
    latitude: 25.30,
    longitude: 91.58,
    rainfall: 168,
    soilMoisture: 79,
    slope: 38,
    historicalEvents: 6,
    historicalRisk: 70,
    riskScore: 70,
    riskLevel: "HIGH",
    recommendedAction: "Issue amber alert to hill communities and keep emergency clearing machinery ready.",
  },
  {
    name: "Gangtok Ridge",
    district: "East Sikkim",
    state: "Sikkim",
    latitude: 27.33,
    longitude: 88.61,
    rainfall: 145,
    soilMoisture: 74,
    slope: 41,
    historicalEvents: 5,
    historicalRisk: 68,
    riskScore: 67,
    riskLevel: "HIGH",
    recommendedAction: "Monitor retaining walls along Indira Bypass and enforce vehicle weight limits.",
  },
  {
    name: "Tawang Pass Slopes",
    district: "Tawang",
    state: "Arunachal Pradesh",
    latitude: 27.58,
    longitude: 91.86,
    rainfall: 142,
    soilMoisture: 72,
    slope: 45,
    historicalEvents: 6,
    historicalRisk: 69,
    riskScore: 69,
    riskLevel: "HIGH",
    recommendedAction: "Pre-position snow and mud clearing equipment along high passes.",
  },
  {
    name: "Bomdila Foothills",
    district: "West Kameng",
    state: "Arunachal Pradesh",
    latitude: 27.26,
    longitude: 92.42,
    rainfall: 138,
    soilMoisture: 70,
    slope: 39,
    historicalEvents: 4,
    historicalRisk: 60,
    riskScore: 64,
    riskLevel: "HIGH",
    recommendedAction: "Check geotechnical sensors along NH-13 corridor.",
  },
  {
    name: "Kohima Slopes",
    district: "Kohima",
    state: "Nagaland",
    latitude: 25.67,
    longitude: 94.11,
    rainfall: 150,
    soilMoisture: 75,
    slope: 37,
    historicalEvents: 5,
    historicalRisk: 65,
    riskScore: 66,
    riskLevel: "HIGH",
    recommendedAction: "Active geotechnical surveillance on unstable sinking zones.",
  },
  {
    name: "Aizawl West Cliffs",
    district: "Aizawl",
    state: "Mizoram",
    latitude: 23.73,
    longitude: 92.71,
    rainfall: 146,
    soilMoisture: 73,
    slope: 42,
    historicalEvents: 5,
    historicalRisk: 67,
    riskScore: 68,
    riskLevel: "HIGH",
    recommendedAction: "Alert local community wardens; monitor building foundation settlement.",
  },
  {
    name: "Lunglei Southern Heights",
    district: "Lunglei",
    state: "Mizoram",
    latitude: 22.89,
    longitude: 92.74,
    rainfall: 135,
    soilMoisture: 69,
    slope: 36,
    historicalEvents: 4,
    historicalRisk: 58,
    riskScore: 62,
    riskLevel: "HIGH",
    recommendedAction: "Inspect slope runoff channels and secure powerline pylons.",
  },
  {
    name: "Senapati Hill Track",
    district: "Senapati",
    state: "Manipur",
    latitude: 25.26,
    longitude: 94.02,
    rainfall: 140,
    soilMoisture: 71,
    slope: 38,
    historicalEvents: 5,
    historicalRisk: 62,
    riskScore: 65,
    riskLevel: "HIGH",
    recommendedAction: "Survey NH-2 highway flanks for tension cracks.",
  },
  {
    name: "Itanagar Papum Hills",
    district: "Papum Pare",
    state: "Arunachal Pradesh",
    latitude: 27.09,
    longitude: 93.62,
    rainfall: 130,
    soilMoisture: 68,
    slope: 34,
    historicalEvents: 4,
    historicalRisk: 55,
    riskScore: 60,
    riskLevel: "HIGH",
    recommendedAction: "Routine patrol of hill-cut colonies and warning sirens tested.",
  },
  {
    name: "Nongpoh Valley Escarpment",
    district: "Ri Bhoi",
    state: "Meghalaya",
    latitude: 25.90,
    longitude: 91.88,
    rainfall: 125,
    soilMoisture: 66,
    slope: 32,
    historicalEvents: 3,
    historicalRisk: 52,
    riskScore: 57,
    riskLevel: "HIGH",
    recommendedAction: "Clear roadside ditches and monitor NH-40 slope stability.",
  },
  {
    name: "Namchi High Ridge",
    district: "South Sikkim",
    state: "Sikkim",
    latitude: 27.17,
    longitude: 88.35,
    rainfall: 122,
    soilMoisture: 65,
    slope: 35,
    historicalEvents: 3,
    historicalRisk: 50,
    riskScore: 56,
    riskLevel: "HIGH",
    recommendedAction: "Inspect agricultural terrace bunds and seepage points.",
  },

  // MODERATE & LOW ZONES (To round out 22 monitored zones)
  {
    name: "Guwahati South Hills",
    district: "Kamrup Metropolitan",
    state: "Assam",
    latitude: 26.14,
    longitude: 91.73,
    rainfall: 98,
    soilMoisture: 52,
    slope: 24,
    historicalEvents: 2,
    historicalRisk: 35,
    riskScore: 44,
    riskLevel: "MODERATE",
    recommendedAction: "Maintain drainage channels in hilly municipal wards.",
  },
  {
    name: "Dimapur Plains Border",
    district: "Dimapur",
    state: "Nagaland",
    latitude: 25.90,
    longitude: 93.73,
    rainfall: 80,
    soilMoisture: 45,
    slope: 16,
    historicalEvents: 1,
    historicalRisk: 25,
    riskScore: 36,
    riskLevel: "MODERATE",
    recommendedAction: "Standard weather monitoring.",
  },
  {
    name: "Imphal Valley Margins",
    district: "Imphal West",
    state: "Manipur",
    latitude: 24.81,
    longitude: 93.93,
    rainfall: 85,
    soilMoisture: 48,
    slope: 18,
    historicalEvents: 1,
    historicalRisk: 28,
    riskScore: 38,
    riskLevel: "MODERATE",
    recommendedAction: "Standard seasonal surveillance.",
  },
  {
    name: "Jowai Plateau",
    district: "West Jaintia Hills",
    state: "Meghalaya",
    latitude: 25.45,
    longitude: 92.20,
    rainfall: 105,
    soilMoisture: 55,
    slope: 26,
    historicalEvents: 2,
    historicalRisk: 38,
    riskScore: 47,
    riskLevel: "MODERATE",
    recommendedAction: "Check mine tailings and quarry slopes for slip lines.",
  },
  {
    name: "Tezpur Foothills",
    district: "Sonitpur",
    state: "Assam",
    latitude: 26.65,
    longitude: 92.79,
    rainfall: 65,
    soilMoisture: 38,
    slope: 12,
    historicalEvents: 0,
    historicalRisk: 15,
    riskScore: 26,
    riskLevel: "LOW",
    recommendedAction: "Normal operations.",
  },
  {
    name: "Agartala Urban Basin",
    district: "West Tripura",
    state: "Tripura",
    latitude: 23.83,
    longitude: 91.28,
    rainfall: 55,
    soilMoisture: 35,
    slope: 8,
    historicalEvents: 0,
    historicalRisk: 10,
    riskScore: 22,
    riskLevel: "LOW",
    recommendedAction: "Normal baseline monitoring.",
  },
  {
    name: "Silchar Plains",
    district: "Cachar",
    state: "Assam",
    latitude: 24.83,
    longitude: 92.78,
    rainfall: 60,
    soilMoisture: 39,
    slope: 9,
    historicalEvents: 0,
    historicalRisk: 12,
    riskScore: 24,
    riskLevel: "LOW",
    recommendedAction: "Normal baseline monitoring.",
  },
];

export const initialRoads: IRoad[] = [
  {
    roadId: "ROAD-NH06",
    name: "NH-6",
    state: "Meghalaya",
    district: "East Jaintia Hills",
    status: "BLOCKED",
    riskScore: 94,
    affectedPopulation: 2840,
    ambulanceAccess: "BLOCKED",
    latitude: 25.18,
    longitude: 92.35,
    priorityRank: 1,
    lastUpdated: new Date().toISOString(),
  },
  {
    roadId: "ROAD-NH10",
    name: "NH-10",
    state: "Sikkim",
    district: "East Sikkim",
    status: "PARTIAL",
    riskScore: 81,
    affectedPopulation: 1240,
    ambulanceAccess: "RESTRICTED",
    latitude: 27.20,
    longitude: 88.55,
    priorityRank: 2,
    lastUpdated: new Date().toISOString(),
  },
  {
    roadId: "ROAD-TAWANG",
    name: "Tawang Highway (Bhalukpong-Tawang)",
    state: "Arunachal Pradesh",
    district: "West Kameng",
    status: "OPEN",
    riskScore: 42,
    affectedPopulation: 540,
    ambulanceAccess: "OPEN",
    latitude: 27.42,
    longitude: 92.15,
    priorityRank: 5,
    lastUpdated: new Date().toISOString(),
  },
  {
    roadId: "ROAD-NH29",
    name: "NH-29 (Dimapur-Kohima)",
    state: "Nagaland",
    district: "Kohima",
    status: "PARTIAL",
    riskScore: 78,
    affectedPopulation: 1850,
    ambulanceAccess: "RESTRICTED",
    latitude: 25.75,
    longitude: 93.95,
    priorityRank: 3,
    lastUpdated: new Date().toISOString(),
  },
  {
    roadId: "ROAD-NH54",
    name: "NH-54 (Silchar-Aizawl)",
    state: "Mizoram",
    district: "Kolasib",
    status: "PARTIAL",
    riskScore: 72,
    affectedPopulation: 1420,
    ambulanceAccess: "RESTRICTED",
    latitude: 24.22,
    longitude: 92.68,
    priorityRank: 4,
    lastUpdated: new Date().toISOString(),
  },
  {
    roadId: "ROAD-SHIL-SOH",
    name: "Shillong-Sohra Road",
    state: "Meghalaya",
    district: "East Khasi Hills",
    status: "BLOCKED",
    riskScore: 92,
    affectedPopulation: 2100,
    ambulanceAccess: "BLOCKED",
    latitude: 25.38,
    longitude: 91.80,
    priorityRank: 2,
    lastUpdated: new Date().toISOString(),
  },
  {
    roadId: "ROAD-NH37",
    name: "NH-37 Southern Bypass",
    state: "Assam",
    district: "Kamrup",
    status: "OPEN",
    riskScore: 35,
    affectedPopulation: 1100,
    ambulanceAccess: "OPEN",
    latitude: 26.08,
    longitude: 91.68,
    priorityRank: 6,
    lastUpdated: new Date().toISOString(),
  },
  {
    roadId: "ROAD-MANGAN-TUN",
    name: "Mangan-Chungthang Road",
    state: "Sikkim",
    district: "North Sikkim",
    status: "BLOCKED",
    riskScore: 89,
    affectedPopulation: 1390,
    ambulanceAccess: "BLOCKED",
    latitude: 27.58,
    longitude: 88.58,
    priorityRank: 3,
    lastUpdated: new Date().toISOString(),
  },
];

export const initialAlerts: IAlert[] = [
  {
    zoneName: "Sohra (Cherrapunji)",
    level: "CRITICAL",
    riskScore: 94,
    message: "High probability of catastrophic landslide detected due to intensifying rainfall (210mm) and critical soil saturation (91%).",
    recommendedAction: "Inspect vulnerable slopes immediately and prepare emergency evacuation routes for valley habitations.",
    status: "ACTIVE",
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  },
  {
    zoneName: "Mangan Valley",
    level: "CRITICAL",
    riskScore: 91,
    message: "Critical debris flow alert triggered by severe continuous precipitation along high mountain slopes.",
    recommendedAction: "Suspend transit along Chungthang corridor; alert district disaster management team.",
    status: "ACTIVE",
    createdAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
  },
  {
    zoneName: "Dima Hasao (Haflong)",
    level: "CRITICAL",
    riskScore: 89,
    message: "Massive mudslide risk near railway cuttings and hillside highway stretches.",
    recommendedAction: "Halt passenger train movement and initiate pre-emptive relocation of track-side hamlets.",
    status: "ACTIVE",
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    zoneName: "Mawsynram Slopes",
    level: "HIGH",
    riskScore: 70,
    message: "Slope saturation reaching threshold limits; localized rockfalls reported on access roads.",
    recommendedAction: "Restrict commercial truck transit and deploy rapid response JCB excavators.",
    status: "ACTIVE",
    createdAt: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
  },
  {
    zoneName: "Tawang Pass Slopes",
    level: "HIGH",
    riskScore: 69,
    message: "Heavy runoff with loose glacial debris threatening road embankments.",
    recommendedAction: "Issue road warning advisory to travelers; inspect culvert drain capacity.",
    status: "ACTIVE",
    createdAt: new Date(Date.now() - 95 * 60 * 1000).toISOString(),
  },
  {
    zoneName: "Shillong Hills",
    level: "HIGH",
    riskScore: 68,
    message: "Water seepage reported along multiple residential retaining walls in Upper Shillong.",
    recommendedAction: "Ward level civil defence volunteers on standby; clear storm drain blockages.",
    status: "ACTIVE",
    createdAt: new Date(Date.now() - 130 * 60 * 1000).toISOString(),
  },
  {
    zoneName: "Kohima Slopes",
    level: "HIGH",
    riskScore: 66,
    message: "Progressive ground cracks observed along downhill side of national highway.",
    recommendedAction: "Divert heavy traffic and establish 24-hour visual slope monitoring.",
    status: "ACTIVE",
    createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
  },
];

// 47 Incidents as requested in Section 34 / Section 6
export const initialIncidents: IIncident[] = [
  {
    incidentId: "INC-2026-08412",
    type: "Blocked Road",
    description: "NH-6 completely blocked near Sonapur tunnel due to heavy rock and mud slide. Ambulances stranded.",
    latitude: 25.18,
    longitude: 92.35,
    locationName: "NH-6 Sonapur Tunnel, East Jaintia Hills",
    severity: "CRITICAL",
    status: "UNDER REVIEW",
    reporter: "Highway Patrol Inspector",
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    incidentId: "INC-2026-08411",
    type: "Ground Crack",
    description: "Major 8-inch wide fissure opened across 40 meters on Sohra upper ridge hillside settlement.",
    latitude: 25.28,
    longitude: 91.72,
    locationName: "Sohra Upper Hillside, East Khasi Hills",
    severity: "CRITICAL",
    status: "VERIFIED",
    reporter: "Village Headman",
    createdAt: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
  },
  {
    incidentId: "INC-2026-08410",
    type: "Slope Movement",
    description: "Active soil creep noticed behind government secondary school slope. Foundation shifting.",
    latitude: 27.52,
    longitude: 88.54,
    locationName: "Mangan Lower Bazaar, North Sikkim",
    severity: "CRITICAL",
    status: "DISPATCHED",
    reporter: "SDRF Sub-Inspector",
    createdAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
  },
  {
    incidentId: "INC-2026-08409",
    type: "Water Seepage",
    description: "Violent muddy water discharge bursting from stone retaining wall at Haflong hill bend.",
    latitude: 25.19,
    longitude: 93.01,
    locationName: "Haflong Hill Road, Dima Hasao",
    severity: "CRITICAL",
    status: "UNDER REVIEW",
    reporter: "PWD Junior Engineer",
    createdAt: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
  },
  {
    incidentId: "INC-2026-08408",
    type: "Rockfall",
    description: "Boulders rolled onto NH-10 near 29th Mile, crushing barrier and stopping uphill lane.",
    latitude: 27.21,
    longitude: 88.56,
    locationName: "NH-10 29th Mile, Sikkim Border",
    severity: "HIGH",
    status: "DISPATCHED",
    reporter: "Border Roads Organisation",
    createdAt: new Date(Date.now() - 105 * 60 * 1000).toISOString(),
  },
  {
    incidentId: "INC-2026-08407",
    type: "Blocked Road",
    description: "Tree and debris fall blocking rural feeder road to Mawmluh limestone quarry.",
    latitude: 25.25,
    longitude: 91.70,
    locationName: "Mawmluh Road, Meghalaya",
    severity: "HIGH",
    status: "VERIFIED",
    reporter: "Local Taxi Driver",
    createdAt: new Date(Date.now() - 140 * 60 * 1000).toISOString(),
  },
  {
    incidentId: "INC-2026-08406",
    type: "Ground Crack",
    description: "Pavement fracturing and sidewalk subsidence along Kohima town bypass.",
    latitude: 25.68,
    longitude: 94.12,
    locationName: "Kohima Town Bypass, Nagaland",
    severity: "HIGH",
    status: "UNDER REVIEW",
    reporter: "Traffic Officer",
    createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
  },
  // Additional realistic incident reports to total exactly 47
  ...Array.from({ length: 40 }).map((_, i) => {
    const types: IIncident["type"][] = [
      "Ground Crack",
      "Slope Movement",
      "Blocked Road",
      "Rockfall",
      "Water Seepage",
    ];
    const severities: IIncident["severity"][] = ["LOW", "MEDIUM", "HIGH"];
    const statuses: IIncident["status"][] = ["VERIFIED", "DISPATCHED", "RESOLVED", "UNDER REVIEW"];
    const locations = [
      "Shillong Peak Link Road",
      "Cherra Bazaar Slope",
      "Gangtok Deorali Ward",
      "Namchi Central Cut",
      "Tawang Gompa Slope",
      "Guwahati Narakasur Hill",
      "Aizawl Durtlang Cliff",
      "Lunglei Bazar Veng",
      "Senapati Karong Road",
      "Itanagar Ganga Lake Turn",
    ];

    const num = (8405 - i).toString().padStart(5, "0");
    const type = types[i % types.length];
    const severity = severities[i % severities.length];
    const status = statuses[i % statuses.length];
    const loc = locations[i % locations.length];

    return {
      incidentId: `INC-2026-${num}`,
      type,
      description: `${type} observed along ${loc}. Minor debris accumulation reported by monitoring volunteer.`,
      latitude: 25.0 + (i % 30) * 0.08,
      longitude: 91.5 + (i % 25) * 0.12,
      locationName: loc,
      severity,
      status,
      reporter: i % 2 === 0 ? "Local Resident Volunteer" : "Civil Defence Patrol",
      createdAt: new Date(Date.now() - (4 + i * 2) * 60 * 60 * 1000).toISOString(),
    };
  }),
];

export const initialSensorLogs: ISensorData[] = [
  {
    zoneName: "Sohra (Cherrapunji)",
    rainfall: 210,
    soilMoisture: 91,
    temperature: 21.4,
    humidity: 96,
    recordedAt: new Date(),
  },
  {
    zoneName: "Mangan Valley",
    rainfall: 195,
    soilMoisture: 88,
    temperature: 17.2,
    humidity: 93,
    recordedAt: new Date(),
  },
  {
    zoneName: "Dima Hasao (Haflong)",
    rainfall: 185,
    soilMoisture: 87,
    temperature: 24.8,
    humidity: 92,
    recordedAt: new Date(),
  },
  {
    zoneName: "Shillong Hills",
    rainfall: 155,
    soilMoisture: 76,
    temperature: 22.0,
    humidity: 91,
    recordedAt: new Date(),
  },
];
